export const USER_REPOSITORY_TOKEN = Symbol('USER_REPOSITORY_TOKEN');
export const USER_SHARE_ACCESS_EVENT = 'USER_SHARE_ACCESS_EVENT';
export const USER_REVOKE_ACCESS_EVENT = 'USER_SHARE_ACCESS_EVENT';
