export const PAYMENT_SERVICE_TOKEN = Symbol('PAYMENT_SERVICE_TOKEN');
export const PAYPAL_AUTH_REQUEST_DELAY_SECONDS = 10;
export const PAYPAL_ACCESS_TOKEN_CACHING_KEY = 'PAYPAL_ACCESS_TOKEN';
export const PAYMENT_PLAN_REPOSITORY_TOKEN = Symbol(
  'PAYMENT_PLAN_REPOSITORY_TOKEN',
);
