import { SubscribeToPayment } from './subscribe-to-payment.interface';

// MOCK AUTOGENERATED TYPE, TODO: move it to the different files and get rid of extra fields
export class PaypalSubscribeBody {
  readonly plan_id: string;
  readonly start_time: string;
  readonly quantity: string;
  readonly shipping_amount: ShippingAmount;
  readonly subscriber: Subscriber;
  readonly application_context: ApplicationContext;

  constructor(planId: string, data: SubscribeToPayment) {
    this.plan_id = planId;

    // convert internal currency to paypal currency
    this.shipping_amount.currency_code = data.subscription.currency;
    this.shipping_amount.value = String(data.subscription.monthlyFee);

		this.start_time = 
  }
}
export interface IPaypalSubscribeBody {
  plan_id: string;
  start_time: string;
  quantity: string;
  shipping_amount: ShippingAmount;
  subscriber: Subscriber;
  application_context: ApplicationContext;
}
interface ShippingAmount {
  currency_code: string;
  value: string;
}
interface Subscriber {
  name: Name;
  email_address: string;
  shipping_address: ShippingAddress;
}
interface Name {
  given_name: string;
  surname: string;
}
interface ShippingAddress {
  name: Name1;
  address: Address;
}
interface Name1 {
  full_name: string;
}
interface Address {
  address_line_1: string;
  address_line_2: string;
  admin_area_2: string;
  admin_area_1: string;
  postal_code: string;
  country_code: string;
}
interface ApplicationContext {
  brand_name: string;
  locale: string;
  shipping_preference: string;
  user_action: string;
  payment_method: PaymentMethod;
  return_url: string;
  cancel_url: string;
}
interface PaymentMethod {
  payer_selected: string;
  payee_preferred: string;
}
