export const FILE_REPOSITORY_TOKEN = Symbol('FILE_REPOSITORY_TOKEN');
export const FILE_STORAGE_SERVICE_TOKEN = Symbol('FILE_STORAGE_SERVICE_TOKEN');
export const FILE_FACADE_TOKEN = Symbol('FILE_FACADE_TOKEN');
export const S3_CLIENT_TOKEN = Symbol('S3_CLIENT_TOKEN');
